bug/urls.py
from django.urls import path

from . import views

app_name = "bug"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.InfoView.as_view(), name="info"),
    # ex: /bug/new/
    path("new/", views.new, name="new"),
    # ex: /bug/save/
    path("save/", views.save, name="save")
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("bug/", include("bug.urls")),
    path('admin/', admin.site.urls),
]

bug/models.py
from django.db import models

# Create your models here.
import datetime

from django.db import models
from django.utils import timezone


class Bug(models.Model):

    BUG_TYPE = [
        ("ERROR", "Error"),
        ("NEW FEATURE", "New Feature"),
        ("INTEGRATION", "Integration"),
        ("OTHER", "Other")
    ]

    STATUS = [
        ("TO DO", "To Do"),
        ("IN PROGRESS", "In Progress"),
        ("DONE", "Done"),
    ]

    description = models.TextField()
    bug_type = models.CharField(max_length=200, choices=BUG_TYPE)
    report_date = models.DateTimeField("Date Reported")
    status = models.CharField(max_length=200, choices=STATUS)

    def __str__(self):
        return self.description

    def was_reported_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.report_date <= now

bug/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Bug


class IndexView(generic.ListView):
    template_name = "bug/index.html"
    context_object_name = "bug_list"

    def get_queryset(self):
        return Bug.objects.filter(report_date__lte=timezone.now()).order_by("-report_date")


class InfoView(generic.DetailView):
    model = Bug
    template_name = "bug/info.html"

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Bug.objects.filter(report_date__lte=timezone.now())


def new(request):
    """
    The fields 'report_date' and 'status' were intentionally left out of the new bug
    registration view to minimize user error in the data. This follows the assumptions
    that admin will be setting the bug status and public users will report the bug
    in a timely manner.
    """
    return render(request, "bug/new.html", {"bug_types": Bug.BUG_TYPE})


def save(request):
   if request.POST["description"] == "":
      return render(
          request,
          "bug/new.html", {
              "error_message": "You did not describe the bug.",
              "bug_types": Bug.BUG_TYPE,
          },
      )
   else:
    b = Bug(description=request.POST["description"],
            bug_type=request.POST["BUG_TYPE"],
            report_date=timezone.now(),
            status="TO DO")
    b.save()
    return HttpResponseRedirect(reverse("bug:info", args=(b.id,)))

bug/templates/bug/index.html
<h1>CapX Bugs Index</h1>
<p>Did you find a bug? Register new bugs here:</p>
<a href="{% url 'bug:new' %}"><b>Submit New Bug</b></a><br>
<h2>List of Bugs:</h2>
{% if bug_list %}
    <ul>
    {% for bug in bug_list %}
        <li><a href="{% url 'bug:info' bug.id %}">{{ bug.description }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No bugs are available.</p>
{% endif %}

bug/templates/bug/info.html
<h1>Registered Bug Information</h1>
<p>Bug Description: {{bug.description}}</p>
<p>Bug Type: {{bug.get_bug_type_display}}</p>
<p>Date Reported: {{bug.report_date}}</p>
<p>Status: {{bug.get_status_display}}</p>

bug/templates/bug/new.html
<form action="{% url 'bug:save' %}" method="post">
{% csrf_token %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<h1>Register a Bug</h1>
<label for="description">Bug Description</label>
<input type="text" name="description" id="description" value=""><br>
    <label for="BUG_TYPE">Bug Type</label>
<select name="BUG_TYPE" id="BUG_TYPE">
    {% for bug_type in bug_types %}
    <option value="{{bug_type.0}}">{{bug_type.1}}</option>
    {% endfor %}

</select><br>
<input type="submit" value="Submit">
</form>